<x-layouts.app title="Mentorship and Professional Growth">
    <section class="bg-isc2-dark-green text-white">
        <div class="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.2fr_.8fr] lg:px-8 lg:py-24">
            <div><p class="mb-4 text-sm font-bold uppercase tracking-widest text-[#9ac23c]">One community. Many pathways.</p><h1 class="max-w-4xl text-4xl font-extrabold leading-tight sm:text-5xl">Find guidance for your next professional step.</h1><p class="mt-6 max-w-2xl text-lg leading-8 text-neutral-200">A structured 18+ mentoring programme for students, career changers, business and governance professionals, cybersecurity practitioners and community contributors.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('register') }}" class="rounded-lg bg-isc2-green px-6 py-3 font-bold text-white hover:bg-[#327137]">Register as a mentor or mentee</a><a href="#pathways" class="rounded-lg border border-white/40 px-6 py-3 font-bold hover:bg-white/10">Explore pathways</a></div></div>
            <div class="rounded-2xl bg-white p-6 text-neutral-950 shadow-2xl"><p class="text-sm font-bold text-isc2-green">How It Works</p><ol class="mt-5 grid gap-5">@foreach(['Create your profile and give matching consent','Complete a short goals and interests assessment','Review a human-approved mentoring proposal','Agree a charter, meet and track progress'] as $item)<li class="flex gap-4"><span class="grid size-8 shrink-0 place-items-center rounded-full bg-isc2-gray font-bold">{{ $loop->iteration }}</span><span>{{ $item }}</span></li>@endforeach</ol></div>
        </div>
    </section>
    <section id="pathways" class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div class="max-w-3xl"><p class="text-sm font-bold uppercase tracking-widest text-isc2-green">Three levels of support</p><h2 class="mt-2 text-3xl font-extrabold">A route forward at every stage</h2></div><div class="mt-8 grid gap-5 md:grid-cols-3">@foreach([['Community mentoring','Webinars, peer circles and office hours for broad access.'],['Matched mentoring','One-to-one or small-cohort relationships for a defined cycle.'],['Specialist mentoring','Advanced technical or leadership support with clear prerequisites.']] as [$name,$description])<article class="rounded-xl border border-neutral-200 p-6"><h3 class="text-xl font-bold">{{ $name }}</h3><p class="mt-3 leading-7 text-neutral-600">{{ $description }}</p></article>@endforeach</div></section>
    <section class="bg-isc2-gray"><div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><h2 class="text-3xl font-extrabold">Programme pathways</h2><div class="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">@foreach(['Explore','Student and University','Career Transition','Employment and Employability','Professional Growth','Advanced Technical','Leadership and Management','Entrepreneurship','Life and Professional Success','Community and Cyber Safety'] as $pathway)<div class="rounded-lg bg-white p-4 font-bold shadow-sm">{{ $pathway }}</div>@endforeach</div></div></section>
</x-layouts.app>
