<x-layouts.app title="Complete Your Profile"><div class="page-shell py-9 sm:py-12"><div class="mx-auto max-w-3xl"><p class="section-kicker">Private participant profile</p><h1 class="mt-1 text-3xl font-extrabold tracking-tight">Tell us what useful support looks like</h1><p class="mt-2 text-sm leading-6 text-neutral-600">Programme staff use this information to make explainable suggestions. Conflict and accessibility details remain restricted.</p><form method="POST" action="{{ route('intake.update') }}" class="panel mt-6 grid gap-5 p-5 sm:p-7">@csrf @method('PUT')
<div class="grid gap-2"><label for="pathway">Primary pathway</label><select id="pathway" name="pathway" required>@foreach(['explore'=>'Explore','student-university'=>'Student and University','career-transition'=>'Career Transition','employment-employability'=>'Employment and Employability','professional-growth'=>'Professional Growth','advanced-technical'=>'Advanced Technical','leadership-management'=>'Leadership and Management','entrepreneurship'=>'Entrepreneurship','life-professional-success'=>'Life and Professional Success','community-cyber-safety'=>'Community and Cyber Safety'] as $value=>$label)<option value="{{ $value }}" @selected(old('pathway',$profile->pathway)===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="grid gap-2"><label for="primary_cluster_id">Primary cluster</label><select id="primary_cluster_id" name="primary_cluster_id" required>@foreach($clusters as $cluster)<option value="{{ $cluster->id }}" @selected((int) old('primary_cluster_id',$profile->primary_cluster_id)===$cluster->id)>{{ $cluster->name }}</option>@endforeach</select></div>
<div class="grid gap-2"><label for="goals">What do you want to achieve in the next 3–6 months?</label><textarea id="goals" name="goals" rows="5" required>{{ old('goals',$profile->goals) }}</textarea>@error('goals')<p class="text-sm text-red-700">{{ $message }}</p>@enderror</div>
<div class="grid gap-2"><label for="experience_summary">What experience and perspective do you bring?</label><textarea id="experience_summary" name="experience_summary" rows="4" required>{{ old('experience_summary',$profile->experience_summary) }}</textarea></div>
<fieldset class="grid gap-3"><legend class="text-sm font-bold">Availability</legend><div class="grid gap-2 sm:grid-cols-2">@foreach(['weekday-morning'=>'Weekday mornings','weekday-afternoon'=>'Weekday afternoons','weekday-evening'=>'Weekday evenings','weekend'=>'Weekends'] as $value=>$label)<label class="flex items-center gap-2 rounded-lg border border-neutral-200 p-3 font-normal"><input type="checkbox" name="availability[]" value="{{ $value }}" @checked(in_array($value,old('availability',$profile->availability??[]),true))>{{ $label }}</label>@endforeach</div></fieldset>
<div class="grid gap-4 sm:grid-cols-2"><div class="grid gap-2"><label for="preferred_language">Preferred language</label><input id="preferred_language" name="preferred_language" value="{{ old('preferred_language',$profile->preferred_language) }}" required></div><div class="grid gap-2"><label for="preferred_format">Meeting format</label><select id="preferred_format" name="preferred_format"><option value="virtual">Virtual</option><option value="in-person">In person</option><option value="hybrid">Hybrid</option></select></div></div>
<div class="grid gap-2"><label for="mentoring_style">Preferred mentoring style</label><textarea id="mentoring_style" name="mentoring_style" rows="3">{{ old('mentoring_style',$profile->mentoring_style) }}</textarea></div>
<div class="grid gap-2"><label for="university_context">University context, if relevant</label><input id="university_context" name="university_context" value="{{ old('university_context',$profile->university_context) }}"></div>
<div class="grid gap-2"><label for="accessibility_needs">Accessibility needs</label><textarea id="accessibility_needs" name="accessibility_needs" rows="3">{{ old('accessibility_needs',$profile->accessibility_needs) }}</textarea><p class="text-sm text-neutral-500">Restricted to staff who need it to arrange participation.</p></div>
<div class="grid gap-2"><label for="conflict_declarations">Relationships or conflicts that should prevent a match</label><textarea id="conflict_declarations" name="conflict_declarations" rows="3">{{ old('conflict_declarations',$profile->conflict_declarations) }}</textarea><p class="text-sm text-neutral-500">This is not shown to mentors or other participants.</p></div>
@if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-red-900"><p class="font-bold">Please correct the form.</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<button class="button-primary sm:justify-self-end">Save and submit for review</button></form></div></div></x-layouts.app>
