<x-layouts.app title="Complete Your Profile"><div class="page-shell py-9 sm:py-14"><div class="content-shell"><p class="section-kicker">Private participant profile</p><h1 class="page-heading mt-1.5">Tell us what useful support looks like</h1><p class="lede mt-3">Programme staff use this information to make explainable suggestions. Conflict and accessibility details remain restricted.</p><form method="POST" action="{{ route('intake.update') }}" class="panel mt-7 grid gap-5 p-5 sm:gap-6 sm:p-8">@csrf @method('PUT')
<fieldset class="grid gap-3"><legend>Primary pathway</legend><p class="field-help">Choose the outcome that best describes what you want from this mentoring cycle. You can update it later.</p><div class="grid gap-3 sm:grid-cols-2">@foreach(config('mentoring.pathways') as $value=>$pathway)<label class="flex cursor-pointer items-start gap-3 rounded-xl border border-neutral-200 bg-neutral-50 p-4 font-normal transition hover:border-isc2-green/40 has-[:checked]:border-isc2-green has-[:checked]:bg-green-50/60"><input class="mt-1" type="radio" name="pathway" value="{{ $value }}" required @checked(old('pathway',$profile->pathway)===$value)><span><span class="block text-sm font-extrabold text-neutral-950">{{ $pathway['label'] }}</span><span class="mt-1 block text-sm leading-5 text-neutral-600">{{ $pathway['description'] }}</span></span></label>@endforeach</div></fieldset>
<div class="grid gap-2"><label for="primary_cluster_id">Primary professional cluster</label><p class="field-help">Select the community of practice most closely connected to your current goal.</p><select id="primary_cluster_id" name="primary_cluster_id" required>@foreach($clusters as $cluster)<option value="{{ $cluster->id }}" @selected((int) old('primary_cluster_id',$profile->primary_cluster_id)===$cluster->id)>{{ $cluster->name }}</option>@endforeach</select></div>
<div class="grid gap-2"><label for="goals">What do you want to achieve in the next 3–6 months?</label><textarea id="goals" name="goals" rows="5" required>{{ old('goals',$profile->goals) }}</textarea>@error('goals')<p class="text-sm text-red-700">{{ $message }}</p>@enderror</div>
<div class="grid gap-2"><label for="experience_summary">What experience and perspective do you bring?</label><textarea id="experience_summary" name="experience_summary" rows="4" required>{{ old('experience_summary',$profile->experience_summary) }}</textarea></div>
<fieldset class="grid gap-3"><legend class="text-sm font-bold">Availability</legend><div class="grid gap-2 sm:grid-cols-2">@foreach(['weekday-morning'=>'Weekday mornings','weekday-afternoon'=>'Weekday afternoons','weekday-evening'=>'Weekday evenings','weekend'=>'Weekends'] as $value=>$label)<label class="flex items-center gap-2 rounded-lg border border-neutral-200 p-3 font-normal"><input type="checkbox" name="availability[]" value="{{ $value }}" @checked(in_array($value,old('availability',$profile->availability??[]),true))>{{ $label }}</label>@endforeach</div></fieldset>
<div class="grid gap-4 sm:grid-cols-2"><div class="grid gap-2"><label for="preferred_language">Preferred language</label><input id="preferred_language" name="preferred_language" value="{{ old('preferred_language',$profile->preferred_language) }}" required></div><div class="grid gap-2"><label for="preferred_format">Meeting format</label><select id="preferred_format" name="preferred_format">@foreach(['virtual'=>'Virtual','in-person'=>'In person','hybrid'=>'Hybrid'] as $value=>$label)<option value="{{ $value }}" @selected(old('preferred_format',$profile->preferred_format)===$value)>{{ $label }}</option>@endforeach</select></div></div>
<div class="grid gap-2"><label for="mentoring_style">Preferred mentoring style</label><textarea id="mentoring_style" name="mentoring_style" rows="3">{{ old('mentoring_style',$profile->mentoring_style) }}</textarea></div>
<div class="grid gap-2"><label for="university_context">University context, if relevant</label><input id="university_context" name="university_context" value="{{ old('university_context',$profile->university_context) }}"></div>
<div class="grid gap-2"><label for="accessibility_needs">Accessibility needs</label><textarea id="accessibility_needs" name="accessibility_needs" rows="3">{{ old('accessibility_needs',$profile->accessibility_needs) }}</textarea><p class="text-sm text-neutral-500">Restricted to staff who need it to arrange participation.</p></div>
<div class="grid gap-2"><label for="conflict_declarations">Relationships or conflicts that should prevent a match</label><textarea id="conflict_declarations" name="conflict_declarations" rows="3">{{ old('conflict_declarations',$profile->conflict_declarations) }}</textarea><p class="text-sm text-neutral-500">This is not shown to mentors or other participants.</p></div>
@if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-red-900"><p class="font-bold">Please correct the form.</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<button class="button-primary w-full sm:w-auto sm:justify-self-end">Save and submit for review</button></form></div></div></x-layouts.app>
