<x-admin.shell title="Propose a mentoring match">
    <form class="panel mx-auto grid max-w-4xl gap-5 p-5 sm:p-7" method="POST" action="{{ route('admin.matches.store') }}">@csrf
        @if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-900"><p class="font-bold">Please review the proposal.</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="grid gap-4 sm:grid-cols-2">
            <div class="field"><label for="mentor_id">Eligible mentor</label><select id="mentor_id" name="mentor_id" required><option value="">Select mentor</option>@foreach($mentors as $mentor)<option value="{{ $mentor->id }}" @selected(old('mentor_id')==$mentor->id)>{{ $mentor->name }} — {{ $mentor->participantProfile->primaryCluster?->name ?? 'Cross-cluster' }} — {{ $mentor->reserved_matches_count }}/{{ $mentor->participantProfile->mentor_capacity }} places used</option>@endforeach</select><p class="field-help">Approved, oriented and available mentors only. Capacity is checked again when saved.</p></div>
            <div class="field"><label for="mentee_id">Approved mentee</label><select id="mentee_id" name="mentee_id" required><option value="">Select mentee</option>@foreach($mentees as $mentee)<option value="{{ $mentee->id }}" @selected(old('mentee_id')==$mentee->id)>{{ $mentee->name }} — {{ config('mentoring.pathways.'.$mentee->participantProfile->pathway.'.label', 'Pathway not selected') }}</option>@endforeach</select><p class="field-help">Only participants approved for matching are listed.</p></div>
        </div>
        <div class="grid gap-4 sm:grid-cols-3"><div class="field"><label for="tier">Tier</label><select id="tier" name="tier">@foreach(['community','matched','specialist'] as $tier)<option value="{{ $tier }}" @selected(old('tier')===$tier)>{{ ucfirst($tier) }}</option>@endforeach</select></div><div class="field"><label for="cluster_id">Cluster</label><select id="cluster_id" name="cluster_id"><option value="">Not assigned</option>@foreach($clusters as $cluster)<option value="{{ $cluster->id }}" @selected(old('cluster_id')==$cluster->id)>{{ $cluster->name }}</option>@endforeach</select></div><div class="field"><label for="compatibility_score">Indicative score</label><input id="compatibility_score" name="compatibility_score" value="{{ old('compatibility_score') }}" type="number" min="0" max="100" placeholder="0–100"></div></div>
        <div class="field"><label for="programme_cycle_id">Programme cycle</label><select id="programme_cycle_id" name="programme_cycle_id"><option value="">Unassigned</option>@foreach($cycles as $cycle)<option value="{{ $cycle->id }}" @selected(old('programme_cycle_id')==$cycle->id)>{{ $cycle->name }}</option>@endforeach</select></div>
        <div class="field"><label for="rationale">Explainable matching rationale</label><textarea id="rationale" name="rationale" rows="6" required placeholder="Describe goal alignment, relevant expertise, availability, format, capacity and conflict checks.">{{ old('rationale') }}</textarea><p class="field-help">Do not include confidential conflict or safeguarding details. The proposal expires after {{ config('mentoring.proposal_expiry_days') }} days if unanswered.</p></div>
        <button class="button-primary justify-self-end">Create proposal</button>
    </form>
</x-admin.shell>
