<x-admin.shell title="Match record">
    <div class="grid gap-5 lg:grid-cols-[1.3fr_.7fr]">
        <div class="space-y-5">
            <section class="panel p-5 sm:p-6">
                <div class="flex items-center justify-between"><p class="section-kicker">{{ ucfirst($match->tier) }} mentoring</p><span class="status-badge">{{ str($match->status)->replace('-',' ')->title() }}</span></div>
                <div class="mt-5 grid gap-4 sm:grid-cols-2"><div class="rounded-xl border border-neutral-200 p-4"><p class="text-xs font-bold text-neutral-500 uppercase">Mentor</p><p class="mt-1 text-lg font-extrabold">{{ $match->mentor->name }}</p><p class="text-sm text-neutral-500">{{ $match->mentor->participantProfile?->primaryCluster?->name }}</p><p class="mt-2 text-xs font-bold text-neutral-500">{{ $match->mentor_confirmed_at ? 'Confirmed '.$match->mentor_confirmed_at->format('j M Y') : 'Awaiting confirmation' }}</p></div><div class="rounded-xl border border-neutral-200 p-4"><p class="text-xs font-bold text-neutral-500 uppercase">Mentee</p><p class="mt-1 text-lg font-extrabold">{{ $match->mentee->name }}</p><p class="text-sm text-neutral-500">{{ $match->mentee->participantProfile?->primaryCluster?->name }}</p><p class="mt-2 text-xs font-bold text-neutral-500">{{ $match->mentee_confirmed_at ? 'Confirmed '.$match->mentee_confirmed_at->format('j M Y') : 'Awaiting confirmation' }}</p></div></div>
                <dl class="mt-5 space-y-4"><div><dt class="text-sm font-bold">Matching rationale</dt><dd class="mt-1 whitespace-pre-line text-sm leading-6 text-neutral-600">{{ $match->rationale }}</dd></div><div><dt class="text-sm font-bold">Context</dt><dd class="mt-1 text-sm text-neutral-600">{{ $match->cluster?->name ?? 'No cluster' }} · {{ $match->programmeCycle?->name ?? 'No cycle' }} · {{ $match->compatibility_score ? $match->compatibility_score.'% indicative compatibility' : 'Manual assessment' }}</dd></div></dl>
            </section>
            <section class="panel p-5 sm:p-6"><div class="flex items-center justify-between"><div><p class="section-kicker">Progress overview</p><h2 class="mt-1 text-xl font-extrabold">Goals and milestones</h2></div>@if(auth()->user()->hasAnyRole(['admin','programme-lead']))<a class="text-sm font-bold text-isc2-green hover:underline" href="{{ route('matches.show',$match) }}">Open workspace</a>@endif</div><div class="mt-5 space-y-3">@forelse($match->goals as $goal)<div class="rounded-lg border border-neutral-200 p-4"><div class="flex items-start justify-between gap-3"><div><p class="font-bold">{{ $goal->title }}</p><p class="mt-1 text-xs text-neutral-500">{{ $goal->milestones->where('status','completed')->count() }} of {{ $goal->milestones->count() }} milestones completed</p></div><span class="status-badge">{{ str($goal->status)->replace('-',' ')->title() }}</span></div></div>@empty<p class="text-sm text-neutral-500">No shared goals yet.</p>@endforelse</div></section>
            @if($match->closure)<section class="panel p-5 sm:p-6"><div class="flex items-start justify-between gap-3"><div><p class="section-kicker">Responsible closure</p><h2 class="mt-1 text-xl font-extrabold">Closure summary</h2></div><span class="status-badge">{{ $match->closure->mentor_confirmed_at && $match->closure->mentee_confirmed_at ? 'Confirmed' : 'Awaiting confirmation' }}</span></div><p class="mt-4 whitespace-pre-line text-sm leading-6 text-neutral-600">{{ $match->closure->summary }}</p>@if($match->closure->next_steps)<p class="mt-4 text-sm font-bold">Next steps</p><p class="mt-1 whitespace-pre-line text-sm leading-6 text-neutral-600">{{ $match->closure->next_steps }}</p>@endif<p class="mt-4 text-xs text-neutral-500">Mentor: {{ $match->closure->mentor_confirmed_at ? 'confirmed' : 'awaiting' }} &middot; Mentee: {{ $match->closure->mentee_confirmed_at ? 'confirmed' : 'awaiting' }}</p>@if($match->status==='closed' && $match->closure->mentor_confirmed_at && $match->closure->mentee_confirmed_at)<a class="button-secondary mt-4" href="{{ route('matches.outcome',$match) }}">Open outcome record</a>@endif</section>@endif
            @if(auth()->user()->hasAnyRole(['admin','programme-lead']))<section class="panel p-5 sm:p-6"><p class="section-kicker">Shared-note oversight</p><h2 class="mt-1 text-xl font-extrabold">Recent participant activity</h2><div class="mt-4 space-y-3">@forelse($match->activities->take(10) as $activity)<div class="border-l-2 border-neutral-300 pl-3"><p class="text-sm leading-6">{{ $activity->body }}</p><p class="text-xs text-neutral-500">{{ $activity->user->name }} · {{ $activity->created_at->diffForHumans() }}</p></div>@empty<p class="text-sm text-neutral-500">No participant activity recorded.</p>@endforelse</div></section>@endif
        </div>
        <aside><form class="panel p-5" method="POST" action="{{ route('admin.matches.update',$match) }}">@csrf @method('PUT')<h2 class="font-extrabold">Record decision</h2><div class="mt-4 field"><label for="status">Status</label><select id="status" name="status">@foreach(['proposed','pending-confirmation','active','declined','rematch-requested','closed'] as $status)<option value="{{ $status }}" @selected($match->status===$status)>{{ str($status)->replace('-',' ')->title() }}</option>@endforeach</select></div><div class="mt-4 field"><label for="reason">Reason</label><textarea id="reason" name="reason" rows="5" required></textarea></div><button class="button-primary mt-4 w-full">Save decision</button></form></aside>
    </div>
</x-admin.shell>
