<x-layouts.app :title="'Mentoring outcome · '.$summary['recordId']">
    <div class="print-record page-shell py-7 sm:py-10">
        <div class="print-hidden mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><a class="text-sm font-bold text-isc2-green hover:underline" href="{{ route('matches.show', $match) }}">&larr; Back to mentoring workspace</a><button type="button" class="button-primary" onclick="window.print()">Print or save as PDF</button></div>

        <article class="mx-auto max-w-4xl">
            <header class="rounded-2xl bg-isc2-dark-green p-6 text-white sm:p-8">
                <div class="flex items-start justify-between gap-5"><div><p class="text-xs font-bold tracking-[0.14em] text-[#9ac23c] uppercase">ISC2 Zimbabwe Chapter</p><h1 class="mt-2 text-3xl font-extrabold tracking-tight sm:text-4xl">Mentoring outcome record</h1><p class="mt-3 text-sm leading-6 text-neutral-200">A concise record of the shared plan and closure confirmed by both participants.</p></div><span class="grid size-12 shrink-0 place-items-center rounded-lg bg-isc2-green text-xs font-extrabold">ISC2</span></div>
                <div class="mt-6 border-t border-white/15 pt-4 text-xs text-neutral-300"><span class="font-bold text-white">Record ID:</span> {{ $summary['recordId'] }} <span class="mx-2">&middot;</span> <span class="font-bold text-white">Closed:</span> {{ $match->closed_at->format('j M Y') }}</div>
            </header>

            <section class="panel mt-5 p-5 sm:p-6"><p class="section-kicker">Relationship</p><dl class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-xs font-bold text-neutral-500 uppercase">Mentor</dt><dd class="mt-1 font-extrabold">{{ $match->mentor->name }}</dd></div><div><dt class="text-xs font-bold text-neutral-500 uppercase">Mentee</dt><dd class="mt-1 font-extrabold">{{ $match->mentee->name }}</dd></div><div><dt class="text-xs font-bold text-neutral-500 uppercase">Started</dt><dd class="mt-1 font-extrabold">{{ $match->started_at?->format('j M Y') ?? 'Not recorded' }}</dd></div><div><dt class="text-xs font-bold text-neutral-500 uppercase">Duration</dt><dd class="mt-1 font-extrabold">{{ $summary['durationDays'] !== null ? $summary['durationDays'].' days' : 'Not recorded' }}</dd></div></dl><p class="mt-5 border-t border-neutral-200 pt-4 text-sm text-neutral-600">{{ $match->cluster?->name ?? 'Cross-cluster mentoring' }}@if($match->programmeCycle) &middot; {{ $match->programmeCycle->name }}@endif</p></section>

            <section class="panel mt-5 overflow-hidden"><div class="panel-header"><div><p class="section-kicker">Shared plan</p><h2 class="mt-1 text-xl font-extrabold">Goals and milestones</h2></div><span class="status-badge">{{ $summary['completedMilestoneCount'] }} of {{ $summary['milestoneCount'] }} milestones complete</span></div><div class="divide-y divide-neutral-200">@forelse($match->goals as $goal)<div class="p-5 sm:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-extrabold">{{ $goal->title }}</h3>@if($goal->description)<p class="mt-1 text-sm leading-6 text-neutral-600">{{ $goal->description }}</p>@endif</div><span class="status-badge">{{ str($goal->status)->replace('-', ' ')->title() }}</span></div>@if($goal->milestones->isNotEmpty())<ul class="mt-4 grid gap-2">@foreach($goal->milestones as $milestone)<li class="flex items-start justify-between gap-3 rounded-lg bg-neutral-50 px-3 py-2 text-sm"><span>{{ $milestone->title }}@if($milestone->owner)<span class="text-neutral-500"> &middot; {{ $milestone->owner->name }}</span>@endif</span><strong class="shrink-0 text-xs">{{ str($milestone->status)->replace('-', ' ')->title() }}</strong></li>@endforeach</ul>@endif</div>@empty<div class="p-6 text-sm text-neutral-500">No formal goals were recorded during this relationship.</div>@endforelse</div></section>

            <section class="panel mt-5 p-5 sm:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="section-kicker">Confirmed closure</p><h2 class="mt-1 text-xl font-extrabold">Outcome and next steps</h2></div><span class="status-badge">Confirmed by both participants</span></div><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><h3 class="text-sm font-extrabold">Shared summary</h3><p class="mt-2 whitespace-pre-line text-sm leading-6 text-neutral-600">{{ $match->closure->summary }}</p></div><div><h3 class="text-sm font-extrabold">Next steps</h3><p class="mt-2 whitespace-pre-line text-sm leading-6 text-neutral-600">{{ $match->closure->next_steps ?: 'No additional next step was recorded.' }}</p></div></div></section>

            <footer class="mt-6 border-t border-neutral-300 pt-4 text-xs leading-5 text-neutral-500"><p>This record confirms participation in a chapter-led mentoring relationship and summarises information recorded by its participants. It is not an ISC2 certification, employment reference, academic credential, or guarantee of professional outcomes.</p><p class="mt-2">Generated {{ now()->format('j M Y') }} from the ISC2 Zimbabwe Chapter Mentorship and Professional Growth Programme.</p></footer>
        </article>
    </div>
</x-layouts.app>
