<x-layouts.app :title="'Mentoring with '.$match->counterpartFor(auth()->user())->name">
    @php($counterpart = $match->counterpartFor(auth()->user()))
    <div class="page-shell py-8 sm:py-12">
        @if(session('status'))<div class="notice-success mb-6">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-6 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-900"><p class="font-bold">Please correct the highlighted information.</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><a class="text-sm font-bold text-isc2-green hover:underline" href="{{ route('matches.index') }}">← My mentoring</a><p class="section-kicker mt-4">{{ ucfirst($match->tier) }} mentoring</p><h1 class="page-heading mt-1.5">Mentoring with {{ $counterpart->name }}</h1></div><span class="status-badge">{{ str($match->status)->replace('-',' ')->title() }}</span></div>

        @if(in_array($match->status,['proposed','pending-confirmation'],true) && $match->involves(auth()->user()))
            @php($confirmed = auth()->id()===$match->mentor_id ? $match->mentor_confirmed_at : $match->mentee_confirmed_at)
            <section class="panel mt-7 p-5 sm:p-6"><p class="section-kicker">Match confirmation</p><h2 class="mt-1 text-xl font-extrabold">{{ $confirmed ? 'Your acceptance is recorded' : 'Review this proposal' }}</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-neutral-600">{{ $match->rationale }}</p>@unless($confirmed)<form method="POST" action="{{ route('matches.confirmation',$match) }}" class="mt-5 flex flex-col gap-3 sm:flex-row">@csrf @method('PUT')<button name="decision" value="accept" class="button-primary">Accept proposed match</button><details class="rounded-lg border border-neutral-200 bg-neutral-50 p-3"><summary class="cursor-pointer text-sm font-bold">Decline with reason</summary><textarea class="mt-3" name="reason" rows="3" placeholder="This is shared with programme staff, not displayed publicly."></textarea><button name="decision" value="decline" class="button-secondary mt-3">Decline proposal</button></details></form>@endunless</section>
        @endif

        @if($match->status === 'active' || $match->goals->isNotEmpty())
        <div class="mt-7 grid gap-6 xl:grid-cols-[1.45fr_.55fr]">
            <div class="space-y-5"><div class="flex items-center justify-between"><div><p class="section-kicker">Shared plan</p><h2 class="section-heading mt-1">Goals and milestones</h2></div></div>
                @forelse($match->goals as $goal)<article class="panel overflow-hidden"><div class="p-5 sm:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="text-lg font-extrabold">{{ $goal->title }}</h3>@if($goal->description)<p class="mt-2 text-sm leading-6 text-neutral-600">{{ $goal->description }}</p>@endif</div><span class="status-badge">{{ str($goal->status)->replace('-',' ')->title() }}</span></div>@if($goal->target_date)<p class="mt-3 text-xs font-bold text-neutral-500">Target {{ $goal->target_date->format('j M Y') }}</p>@endif
                    <div class="mt-5 space-y-2">@foreach($goal->milestones as $milestone)<div class="rounded-lg border border-neutral-200 bg-neutral-50 p-3"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-bold">{{ $milestone->title }}</p><p class="text-xs text-neutral-500">{{ $milestone->due_on?->format('j M Y') ?? 'No due date' }}</p></div><span class="status-badge">{{ str($milestone->status)->replace('-',' ')->title() }}</span></div>@if($match->status==='active')<form method="POST" action="{{ route('milestones.update',$milestone) }}" class="mt-3 grid gap-2 sm:grid-cols-[1fr_1.5fr_auto]">@csrf @method('PUT')<select name="status" aria-label="Milestone status">@foreach(['open','in-progress','completed','blocked'] as $status)<option value="{{ $status }}" @selected($milestone->status===$status)>{{ str($status)->replace('-',' ')->title() }}</option>@endforeach</select><input name="note" placeholder="Optional update note"><button class="button-secondary">Update</button></form>@endif</div>@endforeach</div>
                    @if($match->status==='active')<details class="mt-4 rounded-lg border border-dashed border-neutral-300 p-3"><summary class="cursor-pointer text-sm font-bold text-isc2-green">Add milestone</summary><form method="POST" action="{{ route('milestones.store',$goal) }}" class="mt-3 grid gap-3">@csrf<input name="title" required placeholder="Milestone or target"><textarea name="description" rows="2" placeholder="What will completion look like?"></textarea><input type="date" name="due_on"><button class="button-secondary justify-self-start">Add milestone</button></form></details><form method="POST" action="{{ route('goals.update',$goal) }}" class="mt-4 grid gap-3 border-t border-neutral-200 pt-4 sm:grid-cols-[1fr_1.5fr_auto]">@csrf @method('PUT')<select name="status" aria-label="Goal status">@foreach(['proposed','discussed','agreed','in-progress','completed','paused'] as $status)<option value="{{ $status }}" @selected($goal->status===$status)>{{ str($status)->replace('-',' ')->title() }}</option>@endforeach</select><input name="note" placeholder="Optional note for {{ $counterpart->name }}"><button class="button-primary">Save</button></form>@endif</div></article>@empty<div class="panel p-6 text-center text-sm text-neutral-600">No goals have been added yet. Start by agreeing what success should look like.</div>@endforelse
                @if($match->status==='active')<details class="panel p-5"><summary class="cursor-pointer text-base font-extrabold">Add a shared goal</summary><form method="POST" action="{{ route('goals.store') }}" class="mt-5 grid gap-4">@csrf<input type="hidden" name="mentoring_match_id" value="{{ $match->id }}"><div class="field"><label for="goal_title">Goal title</label><input id="goal_title" name="title" required maxlength="180"></div><div class="field"><label for="goal_description">Description</label><textarea id="goal_description" name="description" rows="4"></textarea></div><div class="field"><label for="goal_target">Target date</label><input id="goal_target" name="target_date" type="date"></div><button class="button-primary justify-self-start">Add goal</button></form></details>@endif
            </div>
            <aside><section class="panel overflow-hidden"><div class="panel-header"><div><p class="section-kicker">Shared record</p><h2 class="font-extrabold">Notes and actions</h2></div></div><div class="max-h-[32rem] space-y-4 overflow-y-auto p-5">@forelse($match->activities as $activity)<div class="border-l-2 {{ $activity->user_id===auth()->id() ? 'border-isc2-green' : 'border-isc2-cornflower' }} pl-3"><p class="text-sm leading-6">{{ $activity->body }}</p><p class="mt-1 text-xs text-neutral-500">{{ $activity->user->name }} · {{ $activity->created_at->diffForHumans() }}</p></div>@empty<p class="text-sm text-neutral-500">No shared activity yet.</p>@endforelse</div>@if($match->status==='active')<form method="POST" action="{{ route('matches.activities.store',$match) }}" class="border-t border-neutral-200 p-4">@csrf<textarea name="body" rows="3" required placeholder="Add a shared note or action update"></textarea><button class="button-primary mt-3 w-full">Post shared note</button></form>@endif</section></aside>
        </div>@endif
    </div>
</x-layouts.app>
